CREATE OR ALTER TRIGGER SELLER_CYCLE_TRIGGER ON Sellers AFTER Update AS 
BEGIN 
    IF EXISTS (SELECT * FROM Sellers as S WHERE dbo.CYCLE_CHECKER(S.seller_id) = 1)
	BEGIN
		RAISERROR('Seller bosses can not form a cycle!', 16, 1);
		ROLLBACK TRANSACTION;
	END
END
GO
